name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: Class.sln
      Test_Project_Path: Class.Tests\Class.Tests.csproj
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
